language: haxe

# NOTE this is just for checking that it is possible to build the ndlls for iOS. It's probably safer to build them
# locally on your own system using your current build of HXCPP and version of Xcode for your own use

# Add secure key for Github
env:
  global:
    - secure: KAHo9/aUa78OeLyd+QXRYbyW41NN6ur52+yOXh81xRJQhqalvwkMfE4rJ0YaPtcXTlmUaZfKseb5egRHMzGAuVoxrj6aYhxS0dVseSNi6izlsfbed8g4O+KgM/aCNySeDlyIeKz6OONQbPBZs9M8IEAoph1fL5Z3LSS8M32hqWkv35BXqa4mCIiNDm0lEl/Z4xZ4xJYjL20zbZdRyqXM0gPUQuvT2rfhAvkpAOe3r5Tbdhc7SQfaYTdjb1wxKDnv/ki1DcxRbSDhP5Gv/H6EL9ZxeUfuWt/b7vV/1ppYq2otd8BrvBKu3W1pUvo5IhdmrxfFTTt92+8tUiNxyelbtqLRsSoSNZb9Sby+AtxFwu4liPDnWum9C/B8TlpoEUWcHctDEMzu49L83nx6mzJQJhOQabH0CgGraIUtA2xyiCtqCDKxMTKU0hVIhCA5w27qW/5TPOYyG7jiawU7nJcypcqiw4PW8NX2Jq/A/uDdGjcsDtsen6+saNRLASMIfUaaNvbCFq0+Vhd3iMJVRCGL2fbe5+GSyGW/rVNRkMf+vvSJq6bCP2BC4kRpdbaig8p4MiNLMHytt6+O3F1LD7RY6Xyh6HsYlt6bDRXRNSUj0grjQKZhfkkGE/9baiTFjkzNcScC2yUelOj4LH5nDXSlR25+wMAKstH1O0RGdgdgchw=

matrix:
  include:
    - os: osx
      osx_image: xcode12.5

# Install dependencies
install:
  - haxelib install hxcpp
  - haxelib install lime
  - haxelib list

# Build the haxelib ndlls
script:
  - pushd project
  - chmod +x rebuild_ndlls.sh
  - ./rebuild_ndlls.sh
  - popd

# Deploy the generated ndlls using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/ndll/
  github_token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
